version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: taxi-admin
    image: taxi-admin